# Generated by Django 5.1.4 on 2025-01-04 18:32

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="CPAPUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hours_used", models.FloatField()),
                ("events_per_hour", models.FloatField()),
                ("mask_leak", models.FloatField()),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("text", "Text"), ("number", "Number")], max_length=10
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_number", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=255)),
                ("policy_number", models.CharField(max_length=100)),
                ("group_number", models.CharField(max_length=100)),
                ("primary_holder", models.CharField(max_length=255)),
                ("relationship", models.CharField(max_length=100)),
                (
                    "authorization_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("authorization_expiry", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SleepStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ahi", models.FloatField()),
                ("sleep_efficiency", models.FloatField()),
                ("rem_latency", models.FloatField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("file_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=100)),
                ("dosage", models.CharField(max_length=100)),
                ("frequency", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Visits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("In-Person", "In-Person"),
                            ("Telehealth", "Telehealth"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                            ("No-Show", "No-Show"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("zoom_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=api.models.Patient.generate_patient_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first", models.CharField(max_length=100)),
                ("middle", models.CharField(blank=True, max_length=100, null=True)),
                ("last", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Inquiry", "Inquiry"),
                            ("Onboarding", "Onboarding"),
                            ("Active", "Active"),
                            ("Churned", "Churned"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("addresses", models.ManyToManyField(blank=True, to="api.address")),
                (
                    "custom_fields",
                    models.ManyToManyField(blank=True, to="api.customfield"),
                ),
                ("insurance", models.ManyToManyField(blank=True, to="api.insurance")),
                ("studies", models.ManyToManyField(blank=True, to="api.sleepstudy")),
                ("treatments", models.ManyToManyField(blank=True, to="api.treatment")),
                ("appointments", models.ManyToManyField(blank=True, to="api.visits")),
            ],
        ),
    ]
