# Generated by Django 5.1.4 on 2025-01-04 18:23

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_address_cpapusage_customfield_insurance_sleepstudy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="id",
            field=models.IntegerField(
                default=api.models.Patient.generate_patient_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
