name: Deploy to DigitalOcean

on:
  push:
    branches: [ main, deployment_debug ]
  workflow_dispatch:

env:
  REGISTRY: "registry.digitalocean.com/stellarcare"
  IMAGE_NAME: "stellarcare"
  NODE_ENV: "production"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Clean up old images
        run: |
          # List and delete old manifests for each tag
          for tag in api web; do
            echo "Cleaning up old images for $tag"
            # List manifests
            manifests=$(doctl registry repository list-manifests ${{ env.IMAGE_NAME }} --output json | jq -r '.[].digest')
            if [ ! -z "$manifests" ]; then
              echo "Found manifests to clean up"
              echo "$manifests" | while read digest; do
                if [ ! -z "$digest" ]; then
                  echo "Deleting manifest: $digest"
                  doctl registry repository delete-manifest ${{ env.IMAGE_NAME }} "$digest" --force || true
                fi
              done
            fi
          done

      - name: Build and push API image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:api-${{ github.sha }} -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:api-latest ./backend
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:api-${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:api-latest

      - name: Build and push Web image
        env:
          BUILD_ENV: "production"
        run: |
          docker build --build-arg BUILD_ENV=production -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:web-${{ github.sha }} -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:web-latest ./frontend
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:web-${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:web-latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create deployment directory
        run: |
          mkdir -p deploy
          cp docker-compose.yaml deploy/
          cp .env.backend deploy/ || echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}" > deploy/.env.backend
          cp .env.frontend deploy/ || echo "NEXT_PUBLIC_API_URL=http://api:8000" > deploy/.env.frontend

      - name: Update docker-compose.yaml
        run: |
          sed -i "s|build:\\s*context:\\s*backend|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:api-${{ github.sha }}|g" deploy/docker-compose.yaml
          sed -i "s|build:\\s*context:\\s*frontend|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:web-${{ github.sha }}|g" deploy/docker-compose.yaml

      - name: Test SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DROPLET_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -vvv ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_HOST }} "echo 'SSH Connection Test Successful'"

      - name: Copy files to droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "deploy/*"
          target: "/opt/stellarcare"
          strip_components: 1
          debug: true
          timeout: 60s
          command_timeout: 30m
          use_insecure_cipher: true

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          debug: true
          script: |
            cd /opt/stellarcare
            docker compose pull
            docker compose down
            docker compose up -d
